### ISSUE TITLE
[FEATURE] basic financial data for individual symbols 

### ISSUE THREAD

**Issue by Shreyaan** [devfinwiz/Fin-Maestro-Kin#27]
**Is your feature request related to a problem? Please describe.**
it would be great to have an endpoint which returns basic financial data like pe ratio for a particular symbol/ equity 

there is an endpoint for index rations but there is none for individual equities 

https://fin-maestro-kin.apidog.io/api-6701895 

**Describe the solution you'd like**
an endpoint which returns basic financial data of a stock for example 

{
    "Symbol Name": "TCS",
    "pe": "23.34",
    "pb": "3.83",
    "divYield": "1.27",
    "DATE": "12 Jan 2024"
  },

**Comment by devfinwiz** [comment]
An endpoint for financial ratios of individual tickers is definitely one of the many things on our to-do list.
We'll try to include it as soon as possible in Fin Maestro Kin.

**Comment by devfinwiz** [comment]
Assigned this ticket to @SuyashDM as he is working on it.
