### ISSUE TITLE
Cloud Agent Error: Can not send requests to localhost:8000.

### ISSUE THREAD

**Issue by Paaarth** [devfinwiz/Fin-Maestro-Kin#39]

**Comment by devfinwiz** [comment]
Can you help me with more details about the issue? 
For eg: 
Which endpoint were you trying to access, how were you trying to access it and what version of the project are you on? 
Logs would be good to have...

**Comment by Paaarth** [comment]
localhost:8000/sentiment/pcr-indice-analysis

**Comment by devfinwiz** [comment]
You are trying to access the wrong endpoint. 
Kindly refer to - https://fin-maestro-kin.apidog.io/api-6701898

**Comment by Paaarth** [comment]
![screenshot-fin-maestro-kin_apidog_io-2024_09_22-11_51_25](https://github.com/user-attachments/assets/0cf3de8a-2b0f-4bcd-95fd-dc326c817f79)

Here it is URL

localhost:8000/sentiment/pcr-stocks-analysis

**Comment by devfinwiz** [comment]
Yes, that's the correct endpoint. I assumed you were trying to access the one under nseindices. Please make sure you have your docker container up. Share the current status of your docker container. If you do not have that up and running, you won't be able to access any of the endpoints.

**Comment by Paaarth** [comment]
Thanks for the response.
Okay, Let me try with that

**Comment by devfinwiz** [comment]
As there were no further comments, I am assuming you were able to resolve the problem at your end. Closing this issue now.
